[env]
_.path = [
    "test/bats/bin",
    "target/debug",
]

[tools]
hadolint = "latest"
ktlint = "latest"
"npm:prettier" = "latest"
"npm:stylelint" = "latest"
pkl = "latest"
shellcheck = "latest"
swiftlint = "latest"
yq = "latest"

[tasks.init]
run = '''
if [ ! -d test/bats ]; then
    git submodule update --init --recursive
fi
'''

[tasks.build]
depends = ["init"]
alias = "b"
run = "cargo build"

[tasks.ci]
depends = ["test", "lint"]

[tasks.test]
alias = ["t"]
depends = ["build"]
run = [
    "cargo test",
    "bats test",
]

[tasks.dist]
run = "pkl project package pkl --output-path docs/public/pkl"

[tasks.prelint]
run = "echo prelint"
[tasks.postlint]
run = "echo postlint"
[tasks.pre-release]
depends = ["render"]
run = "git cliff -o CHANGELOG.md"
[tasks.lint]
depends = ["build"]
run = [
  "hk r co -a",
  "cargo clippy --all-targets --all-features",
]
[tasks.lint-fix]
run = "cargo clippy --fix --allow-dirty --allow-staged --all-targets --all-features"

[tasks.render]
depends = ["build"]
run = [
  "hk usage > hk.usage.kdl",
  "rm -rf docs/cli && mkdir -p docs/cli",
  "usage g markdown -mf hk.usage.kdl --out-dir docs/cli --url-prefix /cli",
  "usage g json -f hk.usage.kdl > docs/cli/commands.json",
  "git add hk.usage.kdl docs",
]
